-- Script para insertar medicamentos de ejemplo usando categorías válidas
INSERT INTO medications (doctor_id, name, generic_name, category, dosage, frequency, typical_duration, instructions, contraindications, side_effects, is_active, created_at, updated_at) VALUES
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Losartán', 'Losartán Potásico', 'Cardiovasculares', '50mg', 'Una vez al día', '30 días', 'Tomar en ayunas, preferiblemente por la mañana', 'Embarazo, hiperpotasemia, estenosis de arteria renal bilateral', 'Mareos, fatiga, tos seca, hiperpotasemia', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Atorvastatina', 'Atorvastatina Cálcica', 'Cardiovasculares', '20mg', 'Una vez al día', '30 días', 'Tomar por la noche con o sin alimentos', 'Enfermedad hepática activa, embarazo, lactancia', 'Dolor muscular, elevación de enzimas hepáticas, cefalea', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Metformina', 'Clorhidrato de Metformina', 'Otros', '500mg', 'Dos veces al día', '30 días', 'Tomar con las comidas para reducir efectos gastrointestinales', 'Insuficiencia renal severa, acidosis metabólica', 'Náuseas, diarrea, dolor abdominal, sabor metálico', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Salbutamol', 'Sulfato de Salbutamol', 'Otros', '100mcg por inhalación', 'Según necesidad', '30 días', 'Inhalar profundamente, máximo 8 inhalaciones por día', 'Hipersensibilidad conocida al salbutamol', 'Temblor, taquicardia, nerviosismo, cefalea', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Omeprazol', 'Omeprazol Magnésico', 'Otros', '20mg', 'Una vez al día', '14-28 días', 'Tomar en ayunas, 30-60 minutos antes del desayuno', 'Hipersensibilidad conocida, uso con atazanavir', 'Cefalea, náuseas, diarrea, dolor abdominal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Aspirina Cardio', 'Ácido Acetilsalicílico', 'Cardiovasculares', '100mg', 'Una vez al día', 'Indefinido', 'Tomar con alimentos, uso prolongado bajo supervisión médica', 'Úlcera péptica activa, hemofilia, alergia a aspirina', 'Dispepsia, sangrado gastrointestinal, tinnitus', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Amlodipino', 'Besilato de Amlodipino', 'Cardiovasculares', '5mg', 'Una vez al día', '30 días', 'Puede tomarse con o sin alimentos, misma hora diariamente', 'Hipersensibilidad, shock cardiogénico, estenosis aórtica severa', 'Edema de tobillos, fatiga, palpitaciones, rubor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Loratadina', 'Loratadina', 'Antihistamínicos', '10mg', 'Una vez al día', '7-14 días', 'Tomar con o sin alimentos, no causa somnolencia', 'Hipersensibilidad conocida', 'Cefalea, fatiga, boca seca, náuseas leves', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Furosemida', 'Furosemida', 'Cardiovasculares', '40mg', 'Una vez al día', '30 días', 'Tomar por la mañana, controlar electrolitos', 'Anuria, hipopotasemia severa, deshidratación', 'Deshidratación, hipopotasemia, mareos, ototoxicidad', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Prednisona', 'Prednisona', 'Corticosteroides', '5mg', 'Según indicación médica', 'Variable', 'Tomar con alimentos, reducir gradualmente la dosis', 'Infecciones sistémicas, úlcera péptica, diabetes no controlada', 'Aumento de peso, retención de líquidos, hiperglucemia', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Ibuprofeno', 'Ibuprofeno', 'Analgésicos', '400mg', 'Cada 8 horas', '7 días', 'Tomar con alimentos para evitar molestias gástricas', 'Úlcera péptica, insuficiencia renal, embarazo tercer trimestre', 'Molestias gástricas, mareos, retención de líquidos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE role = 'doctor' LIMIT 1), 'Amoxicilina', 'Amoxicilina', 'Antibióticos', '500mg', 'Cada 8 horas', '7-10 días', 'Tomar con o sin alimentos, completar todo el tratamiento', 'Alergia a penicilinas, mononucleosis infecciosa', 'Diarrea, náuseas, erupciones cutáneas, candidiasis oral', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
